accent = "#7ca5ff"
cursor = "#f2a0a0"
foreground = "#eaeaef"
background = "#1a1b1e"
selection_foreground = "#2b2d31"
selection_background = "#b2c3ff"

color0 = "#2b2d31"
color1 = "#ef5d67"
color2 = "#8edb73"
color3 = "#f7c553"
color4 = "#7ca5ff"
color5 = "#e29ef3"
color6 = "#7dd8d3"
color7 = "#f8f8fa"
color8 = "#505258"
color9 = "#ff7680"
color10 = "#a2ee8b"
color11 = "#ffd86f"
color12 = "#97b6ff"
color13 = "#efb5f9"
color14 = "#94e8e3"
color15 = "#ffffff"
